### ISSUE TITLE
Dockerfile: missing dependencies especially Werkzeug

### ISSUE THREAD

**Issue by Frosty2500** [rwth-iat/basyx-python-sdk-http-server-docker#8]
Even though our pyproject.toml shows which dependencies we have pip does not seem to recognize or install them. When 
`RUN pip install --no-cache-dir git+https://github.com/rwth-iat/basyx-python-sdk@main` runs Werkzeug is not installed.

**Comment by s-heppner** [comment]
Fixed with #9
